django_project/urls.py
from os import stat
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from .views import AlbumList, AlbumDetail, AlbumCreate, AlbumUpdate, AlbumDelete, UserFormView

app_name = 'music'

urlpatterns = [
	path('', AlbumList.as_view(), name='index'),
	path('album/<int:pk>/', AlbumDetail.as_view(), name='album-detail'),
	path('album/create/', AlbumCreate.as_view(), name='album-create'),
	path('album/<int:pk>/update/', AlbumUpdate.as_view(), name='album-update'),
	path('album/<int:pk>/delete/', AlbumDelete.as_view(), name='album-delete'),

	path('register/', UserFormView.as_view(), name='register')
]

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    album_title = models.CharField(max_length=250)
    artist = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    album_logo = models.ImageField(upload_to='album/images/')
    
    def __str__(self):
        return f'{self.album_title} - {self.artist}'
    
    def get_absolute_url(self):
        return reverse('music:album-detail', kwargs={'pk': self.pk })


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    file_type = models.CharField(max_length=20)
    
    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Album
from django.urls import reverse_lazy

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm


class AlbumList(ListView):
    model = Album
    template_name = 'music/index.html'
    context_object_name = 'albums'


class AlbumDetail(DetailView):
    model = Album
    template_name = 'music/album-detail.html'
    context_object_name = 'album'


class AlbumCreate(CreateView):
    model = Album
    fields = ['album_title', 'artist', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['album_title', 'artist', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
                
        return render(request, self.template_name, {'form': form})

music/templates/music/album-delete.html
<div class="modal" tabindex="-1" id="delete-album-{{ album.id }}">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete Album</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete <strong>{{ album.album_title }}</strong>?</p>
			</div>
			<div class="modal-footer">
				<form action="{% url 'music:album-delete' album.id %}" method="POST">
					{% csrf_token %}
					<button type="submit" class="btn btn-outline-danger">Delete</button>
				</form>
			</div>
		</div>
	</div>
</div>

music/templates/music/album-detail.html
{% extends "music/base.html"%}
{% block content %}
<div class="row">
	<div class="col-md-3 album">
		<div class="card">
			<img src="{{ album.album_logo.url }}" class="card-img-top" alt="...">
			<div class="card-body">
				<h5 class="card-title">{{ album.album_title }}</h5>
				<p class="card-text mb-1 text-muted">Artist: {{ album.artist }}</p>
				<p class="card-text text-muted">Genre: {{ album.genre }}</p>
				<a href="{% url 'music:album-update' album.id %}" class="btn btn-outline-secondary"><i class="fas fa-pencil-alt me-2"></i>Update</a>
			</div>
		</div>
	</div>
	<div class="col-md-9 songs">
		<h4 class="mb-4">Songs</h4>
		{% for song in album.song_set.all %}
		<p class="rounded p-2 m-0 border border-white" id="album-song">{{ forloop.counter }}. {{ song }}</p>
		{% endfor %}
	</div>

</div>
{% endblock %}

music/templates/music/album_form.html
{% extends "music/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-7 offset-lg-2 col-md-10 create-form">
	 <h4 class="mb-4">Add Album</h4>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-secondary mt-4">Save</button>
	</form>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
		integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
		crossorigin="anonymous" />
	<link rel="stylesheet" href="{% static 'music/main.css' %}">
	<title>Music</title>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container-fluid">
			<a class="navbar-brand ms-2 me-5" href="{% url 'music:index' %}">melody</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item me-2">
						<a class="nav-link" href="{% url 'music:index' %}"><i class="fas fa-compact-disc me-2"></i>Albums</a>
					</li>
					<li class="nav-item me-5">
						<a class="nav-link" href="#"><i class="fas fa-music me-2"></i>Songs</a>
					</li>
					<form class="d-flex">
						<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
						<button class="btn btn-outline-secondary" type="submit">Search</button>
					</form>
				</ul>
				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
					<li class="nav-item me-2">
						<a class="nav-link" href="{% url 'music:album-create' %}"><i class="fas fa-plus me-2"></i>Add Album</a>
					</li>
					<li class="nav-item me-2">
						<a class="nav-link" href="#"><i class="fas fa-power-off me-2"></i>Logout</a>
					</li>
				</ul>

			</div>
		</div>
	</nav>

	<div class="container">
		{% block content %}
		{% endblock %}
	</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
		crossorigin="anonymous"></script>
</body>

</html>

music/templates/music/index.html
{% extends "music/base.html"%}
{% block content %}
<div class="row">
	{% for album in albums %}
	<div class="col-lg-4 col-md-6 album">
		<div class="card">
			<img src="{{ album.album_logo.url }}" class="card-img-top p-2" alt="..." height="350">
			<div class="card-body pt-1 pb-1">
				<div class="d-flex bd-highlight">
					<h5 class="card-title">{{ album.album_title }}</h5>
					<p class="card-text ms-2">by {{ album.artist }}</p>
				</div>
				<div class="d-flex bd-highlight mt-2">
					<div class="pb-2 bd-highlight">
						<a href="{% url 'music:album-detail' album.id %}" class="btn btn-outline-secondary">View
							Detail</a>
					</div>

					<div class="ms-auto bd-highlight">
						<a class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#delete-album-{{ album.id }}"><i
								class="fas fa-trash"></i></a>
					</div>
					{% include 'music/album-delete.html' %}
				</div>
			</div>
		</div>
	</div>
	
	{% endfor %}
</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends "music/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-7 offset-lg-2 col-md-10 create-form">
	 <h4 class="mb-4">Register User</h4>
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-secondary mt-4">Create User</button>
	</form>
</div>
{% endblock %}